// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAiNPFPqMQOO0FMVpbB4ntLgj9SukTjU',
    appId: '1:869131519394:web:661f0892191b63d5781efb',
    messagingSenderId: '869131519394',
    projectId: 'wordle-aff65',
    authDomain: 'wordle-aff65.firebaseapp.com',
    storageBucket: 'wordle-aff65.firebasestorage.app',
    measurementId: 'G-7QGMLQT8NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6sfWzcq7F1k5TnvBQ5MStO-r8Pk2Md0',
    appId: '1:869131519394:android:0827b1805128fa83781efb',
    messagingSenderId: '869131519394',
    projectId: 'wordle-aff65',
    storageBucket: 'wordle-aff65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdSntksvmNe7xRn7y5cWGqQbASZYxE7k',
    appId: '1:869131519394:ios:83b8ac897b00e391781efb',
    messagingSenderId: '869131519394',
    projectId: 'wordle-aff65',
    storageBucket: 'wordle-aff65.firebasestorage.app',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdSntksvmNe7xRn7y5cWGqQbASZYxE7k',
    appId: '1:869131519394:ios:83b8ac897b00e391781efb',
    messagingSenderId: '869131519394',
    projectId: 'wordle-aff65',
    storageBucket: 'wordle-aff65.firebasestorage.app',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxAiNPFPqMQOO0FMVpbB4ntLgj9SukTjU',
    appId: '1:869131519394:web:f41988c329a79a60781efb',
    messagingSenderId: '869131519394',
    projectId: 'wordle-aff65',
    authDomain: 'wordle-aff65.firebaseapp.com',
    storageBucket: 'wordle-aff65.firebasestorage.app',
    measurementId: 'G-5MTXN9T3HM',
  );
}
